const ProyectsActionTypes = {
  ADD_PROYECT_START: "ADD_PROYECT_START",
  ADD_PROYECT_COMPLETE: "ADD_PROYECT_COMPLETE",
  DELETE_PROYECT: "DELETE_PROYECT"
};

export default ProyectsActionTypes;

export const ProyectTypes = {
  MEDICION_DE_DISTANCIAS_CINTA: "MEDICION_DE_DISTANCIAS_CINTA",
  MEDICION_DE_ANGULOS_CON_CINTA: "MEDICION_DE_ANGULOS_CON_CINTA",
  LEVANTAMIENTO_PLANIMETRICO_CON_CINTA: "LEVANTAMIENTO_PLANIMETRICO_CON_CINTA"
};
